/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Gateway Dev API
 * This is an API for interacting with the Transportation Data Equity Initiative (TDEI) system. It is intended for applications submitting data to and consuming data from the TDEI system. We currently support GTFS-Pathways, GTFS-Flex and OpenSidewalks (OSW) data schemas.
 *
 * OpenAPI spec version: v0.1
 * Contact: helpdesk@tdei.us
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * QualityReportApi - axios parameter creator
 * @export
 */
export const QualityReportApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Initiates the Quality report generation for requested `tdei_dataset_id`. The response includes a `job_id` for tracking the request.To check the request status, refer to the location header in the response, which provides the URL for the status API endpoint.
         * @summary Initiate Quality report generation for a dataset
         * @param {string} tdei_dataset_id Dataset id of the dataset for which Quality report is to be generated.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oswQualityReportGenerate: async (tdei_dataset_id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tdei_dataset_id' is not null or undefined
            if (tdei_dataset_id === null || tdei_dataset_id === undefined) {
                throw new RequiredError('tdei_dataset_id','Required parameter tdei_dataset_id was null or undefined when calling oswQualityReportGenerate.');
            }
            const localVarPath = `/api/v1/osw/quality-report/{tdei_dataset_id}`
                .replace(`{${"tdei_dataset_id"}}`, encodeURIComponent(String(tdei_dataset_id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthorizationToken required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QualityReportApi - functional programming interface
 * @export
 */
export const QualityReportApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Initiates the Quality report generation for requested `tdei_dataset_id`. The response includes a `job_id` for tracking the request.To check the request status, refer to the location header in the response, which provides the URL for the status API endpoint.
         * @summary Initiate Quality report generation for a dataset
         * @param {string} tdei_dataset_id Dataset id of the dataset for which Quality report is to be generated.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async oswQualityReportGenerate(tdei_dataset_id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await QualityReportApiAxiosParamCreator(configuration).oswQualityReportGenerate(tdei_dataset_id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * QualityReportApi - factory interface
 * @export
 */
export const QualityReportApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Initiates the Quality report generation for requested `tdei_dataset_id`. The response includes a `job_id` for tracking the request.To check the request status, refer to the location header in the response, which provides the URL for the status API endpoint.
         * @summary Initiate Quality report generation for a dataset
         * @param {string} tdei_dataset_id Dataset id of the dataset for which Quality report is to be generated.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async oswQualityReportGenerate(tdei_dataset_id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return QualityReportApiFp(configuration).oswQualityReportGenerate(tdei_dataset_id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QualityReportApi - object-oriented interface
 * @export
 * @class QualityReportApi
 * @extends {BaseAPI}
 */
export class QualityReportApi extends BaseAPI {
    /**
     * Initiates the Quality report generation for requested `tdei_dataset_id`. The response includes a `job_id` for tracking the request.To check the request status, refer to the location header in the response, which provides the URL for the status API endpoint.
     * @summary Initiate Quality report generation for a dataset
     * @param {string} tdei_dataset_id Dataset id of the dataset for which Quality report is to be generated.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QualityReportApi
     */
    public async oswQualityReportGenerate(tdei_dataset_id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return QualityReportApiFp(this.configuration).oswQualityReportGenerate(tdei_dataset_id, options).then((request) => request(this.axios, this.basePath));
    }
}
