---
######### Dev Workflow  ########
on:
  workflow_dispatch:
    inputs:
      endpoint:
        description: "Open API spec spec_url"
        required: true

jobs:
  GenerateAPIClient:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate API Client
        run: |
          bash autogenerate_api_client.sh ${{github.event.inputs.endpoint}}
