/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Gateway Dev API
 * This is an API for interacting with the Transportation Data Equity Initiative (TDEI) system. It is intended for applications submitting data to and consuming data from the TDEI system. We currently support GTFS-Pathways, GTFS-Flex and OpenSidewalks (OSW) data schemas.
 *
 * OpenAPI spec version: v0.1
 * Contact: tdei@uw.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Response model for API versions
 * @export
 * @interface APIVersionSpec
 */
export interface APIVersionSpec {
    /**
     * Version of the API
     * @type {string}
     * @memberof APIVersionSpec
     */
    version?: string;
    /**
     * Link to the API documentation.
     * @type {string}
     * @memberof APIVersionSpec
     */
    documentation?: string;
    /**
     * Link to the API specification.
     * @type {string}
     * @memberof APIVersionSpec
     */
    specification?: string;
}
