/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Gateway Dev API
 * This is an API for interacting with the Transportation Data Equity Initiative (TDEI) data system. It is intended for applications producing data to and consuming data from the TDEI system. It currently supports GTFS-Pathways, GTFS-Flex v2 and OpenSidewalks v0.2 data schemas.
 *
 * OpenAPI spec version: v0.1
 * Contact: tdei@uw.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Maintenance details of the dataset
 * @export
 * @interface MetadataModelMaintenance
 */
export interface MetadataModelMaintenance {
    /**
     * Official maintainer of the dataset
     * @type {Array<string>}
     * @memberof MetadataModelMaintenance
     */
    official_maintainer?: Array<string>;
    /**
     * Date when the dataset was last updated
     * @type {string}
     * @memberof MetadataModelMaintenance
     */
    last_updated?: string;
    /**
     * Frequency of updates
     * @type {string}
     * @memberof MetadataModelMaintenance
     */
    update_frequency?: string;
    /**
     * Authorization chain
     * @type {string}
     * @memberof MetadataModelMaintenance
     */
    authorization_chain?: string;
    /**
     * Is maintenance funded
     * @type {boolean}
     * @memberof MetadataModelMaintenance
     */
    maintenance_funded?: boolean;
    /**
     * Funding details
     * @type {string}
     * @memberof MetadataModelMaintenance
     */
    funding_details?: string;
}
