/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Gateway Dev API
 * This is an API for interacting with the Transportation Data Equity Initiative (TDEI) system. It is intended for applications submitting data to and consuming data from the TDEI system. We currently support GTFS-Pathways, GTFS-Flex and OpenSidewalks (OSW) data schemas.
 *
 * OpenAPI spec version: v0.1
 * Contact: tdei@uw.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MetadataModelDataProvenance
 */
export interface MetadataModelDataProvenance {
    /**
     * Full name of the dataset
     * @type {string}
     * @memberof MetadataModelDataProvenance
     */
    full_dataset_name?: string;
    /**
     * Other published locations
     * @type {string}
     * @memberof MetadataModelDataProvenance
     */
    other_published_locations?: string;
    /**
     * Dataset update frequency in months
     * @type {number}
     * @memberof MetadataModelDataProvenance
     */
    dataset_update_frequency_months?: number;
    /**
     * Is schema validation run
     * @type {boolean}
     * @memberof MetadataModelDataProvenance
     */
    schema_validation_run?: boolean;
    /**
     * Description of schema validation run
     * @type {string}
     * @memberof MetadataModelDataProvenance
     */
    schema_validation_run_description?: string;
    /**
     * Is crowd contributions allowed
     * @type {boolean}
     * @memberof MetadataModelDataProvenance
     */
    allow_crowd_contributions?: boolean;
    /**
     * Location inaccuracy factors
     * @type {string}
     * @memberof MetadataModelDataProvenance
     */
    location_inaccuracy_factors?: string;
}
