/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Gateway API
 * This is an API for publishing data to the Transportation Data Equity Initiative (TDEI) data system. This API is intended for applications producing data for and consuming data from the TDEI system. This API supports publishing of GTFS-Pathways, GTFS-Flex v2 and OpenSidewalks data to the TDEI.
 *
 * OpenAPI spec version: v0.1
 * Contact: placeholder_support@transequity.cs.washington.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoJsonObject } from './geo-json-object';
/**
 * represents a osw data file.
 * @export
 * @interface OswDownload
 */
export interface OswDownload {
    /**
     * tdei-assigned organization id. Represented as UUID. Organization ids can be retrieved using the /api/v1/organizations path.
     * @type {string}
     * @memberof OswDownload
     */
    tdeiOrgId: string;
    /**
     * Description of who data was collected by. See Best Practices document for information on how to format this string.
     * @type {string}
     * @memberof OswDownload
     */
    collectedBy: string;
    /**
     * date-time that data was collected
     * @type {string}
     * @memberof OswDownload
     */
    collectionDate: string;
    /**
     * Method by which the data was collected. See Best Practices document for information on how to format this string.
     * @type {string}
     * @memberof OswDownload
     */
    collectionMethod: OswDownloadCollectionMethodEnum;
    /**
     * Date of publication of the file
     * @type {string}
     * @memberof OswDownload
     */
    publicationDate?: string;
    /**
     * tdei-generated confidence level. Confidence level range is: 0 (very low confidence) to 100 (very high confidence).
     * @type {number}
     * @memberof OswDownload
     */
    confidenceLevel: number;
    /**
     * Description of data source or sources from which the data was collected. See Best Practices document for information on how to format this string.
     * @type {string}
     * @memberof OswDownload
     */
    dataSource: OswDownloadDataSourceEnum;
    /**
     * 
     * @type {GeoJsonObject}
     * @memberof OswDownload
     */
    polygon: GeoJsonObject;
    /**
     * unique id identifying the file in the tdei system, can be used to retrieve the file itself.
     * @type {string}
     * @memberof OswDownload
     */
    tdeiRecordId: string;
    /**
     * version of osw schema this file conforms to
     * @type {string}
     * @memberof OswDownload
     */
    oswSchemaVersion: string;
    /**
     * The url from which this file can be downloaded.
     * @type {string}
     * @memberof OswDownload
     */
    downloadUrl: string;
}

/**
    * @export
    * @enum {string}
    */
export enum OswDownloadCollectionMethodEnum {
    Manual = 'manual',
    Transform = 'transform',
    Generated = 'generated',
    Other = 'other'
}
/**
    * @export
    * @enum {string}
    */
export enum OswDownloadDataSourceEnum {
    _3rdParty = '3rdParty',
    TDEITools = 'TDEITools',
    InHouse = 'InHouse'
}

