/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Gateway Dev API
 * This is an API for interacting with the Transportation Data Equity Initiative (TDEI) system. It is intended for applications submitting data to and consuming data from the TDEI system. We currently support GTFS-Pathways, GTFS-Flex and OpenSidewalks (OSW) data schemas.
 *
 * OpenAPI spec version: v0.1
 * Contact: admin@tdei.us
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OswSpatialjoinBody
 */
export interface OswSpatialjoinBody {
    /**
     * Unique dataset id defined in TDEI system
     * @type {string}
     * @memberof OswSpatialjoinBody
     */
    target_dataset_id: string;
    /**
     * Valid opensidewalks core entity on which the join operation is to be performed
     * @type {string}
     * @memberof OswSpatialjoinBody
     */
    target_dimension: OswSpatialjoinBodyTargetDimensionEnum;
    /**
     * Unique dataset id defined in TDEI system
     * @type {string}
     * @memberof OswSpatialjoinBody
     */
    source_dataset_id: string;
    /**
     * Valid opensidewalks core entity on which the join operation is to be performed
     * @type {string}
     * @memberof OswSpatialjoinBody
     */
    source_dimension: OswSpatialjoinBodySourceDimensionEnum;
    /**
     * Condition on which target and source geometry will join. geometry_target & geometry_source are constant variable representing the element geometry. 
     * @type {string}
     * @memberof OswSpatialjoinBody
     */
    join_condition: string;
    /**
     * Target attribute filters. These can be any valid attributes defined in the OpenSidewalks schema for the entity.
     * @type {string}
     * @memberof OswSpatialjoinBody
     */
    join_filter_target?: string;
    /**
     * Source attribute filters, These can be any valid attributes defined in the OpenSidewalks schema for the entity
     * @type {string}
     * @memberof OswSpatialjoinBody
     */
    join_filter_source?: string;
    /**
     * Agrregate function for attribute. Attribute information to be pulled along from source and attach to target dataset entity. All attribute_name/alias will be prefixed with 'ext:'
     * @type {Array<string>}
     * @memberof OswSpatialjoinBody
     */
    aggregate?: Array<string>;
}

/**
    * @export
    * @enum {string}
    */
export enum OswSpatialjoinBodyTargetDimensionEnum {
    Edge = 'edge',
    Node = 'node',
    Zone = 'zone'
}
/**
    * @export
    * @enum {string}
    */
export enum OswSpatialjoinBodySourceDimensionEnum {
    Edge = 'edge',
    Node = 'node',
    Zone = 'zone',
    Point = 'point',
    Line = 'line',
    Polygon = 'polygon'
}

