/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Gateway API
 * This is an API for publishing data to the Transportation Data Equity Initiative (TDEI) data system. This API is intended for applications producing data for and consuming data from the TDEI system. This API supports publishing of GTFS-Pathways, GTFS-Flex v2 and OpenSidewalks data to the TDEI.
 *
 * OpenAPI spec version: v0.1
 * Contact: placeholder_support@transequity.cs.washington.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface OSWFormatStatusResponse
 */
export interface OSWFormatStatusResponse {

    /**
     * jobId of the format request
     *
     * @type {string}
     * @memberof OSWFormatStatusResponse
     */
    jobId: string;

    /**
     * Status of the format request
     *
     * @type {string}
     * @memberof OSWFormatStatusResponse
     */
    status?: OSWFormatStatusResponseStatusEnum;

    /**
     * Any error message during failure
     *
     * @type {string}
     * @memberof OSWFormatStatusResponse
     */
    message?: string;

    /**
     * URL of the source file
     *
     * @type {string}
     * @memberof OSWFormatStatusResponse
     */
    sourceUrl?: string;

    /**
     * URL of the target file
     *
     * @type {string}
     * @memberof OSWFormatStatusResponse
     */
    targetUrl?: string;

    /**
     * type of conversion
     *
     * @type {string}
     * @memberof OSWFormatStatusResponse
     * @example osw-osm
     */
    conversion?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum OSWFormatStatusResponseStatusEnum {
    Started = 'started',
    Completed = 'completed',
    Failed = 'failed'
}

