/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Gateway Dev API
 * This is an API for interacting with the Transportation Data Equity Initiative (TDEI) system. It is intended for applications submitting data to and consuming data from the TDEI system. We currently support GTFS-Pathways, GTFS-Flex and OpenSidewalks (OSW) data schemas.
 *
 * OpenAPI spec version: v0.1
 * Contact: admin@tdei.us
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { POC } from './poc';
import { Polygon } from './polygon';
import { ProjectGroupDataViewer } from './project-group-data-viewer';
/**
 * 
 * @export
 * @interface ProjectGroup
 */
export interface ProjectGroup {
    /**
     * ProjectGroupId uniquely represented in the TDEI system. System generated.
     * @type {string}
     * @memberof ProjectGroup
     */
    tdei_project_group_id?: string;
    /**
     * Name of the project group.
     * @type {string}
     * @memberof ProjectGroup
     */
    name?: string;
    /**
     * Phone of the project group for communication.
     * @type {string}
     * @memberof ProjectGroup
     */
    phone?: string;
    /**
     * Url of the transit project group.
     * @type {string}
     * @memberof ProjectGroup
     */
    url?: string;
    /**
     * Address of the transit project group.
     * @type {string}
     * @memberof ProjectGroup
     */
    address?: string;
    /**
     * 
     * @type {Polygon}
     * @memberof ProjectGroup
     */
    polygon: Polygon;
    /**
     * Project group POC details
     * @type {Array<POC>}
     * @memberof ProjectGroup
     */
    poc?: Array<POC>;
    /**
     * 
     * @type {ProjectGroupDataViewer}
     * @memberof ProjectGroup
     */
    data_viewer?: ProjectGroupDataViewer;
}
