/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Gateway Dev API
 * This is an API for interacting with the Transportation Data Equity Initiative (TDEI) system. It is intended for applications submitting data to and consuming data from the TDEI system. We currently support GTFS-Pathways, GTFS-Flex and OpenSidewalks (OSW) data schemas.
 *
 * OpenAPI spec version: v0.1
 * Contact: helpdesk@tdei.us
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RefreshTokenRequest
 */
export interface RefreshTokenRequest {
    /**
     * The refresh token returned from authenticate, sso-login, or a previous refresh-token call.
     * @type {string}
     * @memberof RefreshTokenRequest
     */
    refresh_token: string;
    /**
     * Keycloak client id used for the token refresh. Optional; defaults to the configured default client id when not provided. Should match the client used when the original tokens were issued.
     * @type {string}
     * @memberof RefreshTokenRequest
     */
    client_id?: string;
}
