/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Gateway Dev API
 * This is an API for interacting with the Transportation Data Equity Initiative (TDEI) system. It is intended for applications submitting data to and consuming data from the TDEI system. We currently support GTFS-Pathways, GTFS-Flex and OpenSidewalks (OSW) data schemas.
 *
 * OpenAPI spec version: v0.1
 * Contact: admin@tdei.us
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ServiceMetricsProjectGroup } from './service-metrics-project-group';
import { ServiceMetricsServices } from './service-metrics-services';
/**
 * 
 * @export
 * @interface ServiceMetrics
 */
export interface ServiceMetrics {
    /**
     * 
     * @type {ServiceMetricsProjectGroup}
     * @memberof ServiceMetrics
     */
    project_group: ServiceMetricsProjectGroup;
    /**
     * 
     * @type {Array<ServiceMetricsServices>}
     * @memberof ServiceMetrics
     */
    services: Array<ServiceMetricsServices>;
}
