/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Gateway Dev API
 * This is an API for interacting with the Transportation Data Equity Initiative (TDEI) system. It is intended for applications submitting data to and consuming data from the TDEI system. We currently support GTFS-Pathways, GTFS-Flex and OpenSidewalks (OSW) data schemas.
 *
 * OpenAPI spec version: v0.1
 * Contact: helpdesk@tdei.us
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Optional settings for a single OSW file type during union. Every property is optional.
 * @export
 * @interface UnionEntityFilterBlock
 */
export interface UnionEntityFilterBlock {
    /**
     * Attribute filter groups for this file type. Each group is an object of OpenSidewalks attribute/value pairs (or `ext:*` extensions). Features must match at least one group to be eligible. An empty group is not allowed.
     * @type {Array<{ [key: string]: string; }>}
     * @memberof UnionEntityFilterBlock
     */
    filters?: Array<{ [key: string]: string; }>;
    /**
     * Corridor width in metres used when detecting duplicate linear features. Supported for `edge` and `line` only. Must be greater than 0.
     * @type {number}
     * @memberof UnionEntityFilterBlock
     */
    duplicate_buffer_width?: number;
    /**
     * Minimum overlap percentage (greater than 0 and at most 100) used when detecting duplicate features. Supported for `edge`, `line`, `polygon`, and `zone`. Not supported for `node` or `point`, which are merged by proximity.
     * @type {number}
     * @memberof UnionEntityFilterBlock
     */
    duplicate_overlap_percentage?: number;
}
